spring.application.name=medisphere-AIsymptomcheck-service
server.port=8088

# Data Source configuration
spring.datasource.url=jdbc:postgresql://ep-spring-haze-a1my82ya-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q4AfizWR1LlF
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator for monitoring
management.endpoints.web.exposure.include=health,info

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

# GROQ API
groq.api-url=https://api.groq.com/openai/v1/chat/completions
groq.api-key=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

# JWT (same secret as all other services)
jwt.secret=your_very_secure_and_long_secret_key_for_medisphere_telemedicine_service_2026


# Disable open-in-view
spring.jpa.open-in-view=false

# Logging
logging.level.com.medisphere=DEBUG